'----------- Compétences

package Competence1 {
rectangle "APC11 : Implementer des conceptions simples" as APC11 
rectangle "APC12 : Elaborer des conceptions simples" as APC12
rectangle "APC13 : Faire des essais et evaluer leurs resultats en regard des specifications" as APC13
rectangle "APC14 : Developper des interfaces utilisateur" as APC14
}

package Competence2 {
rectangle "APC21 : Analyser un problème avec méthode" as APC21 
rectangle "APC22 : Comparer des algo pour des pb classiques" as APC22
rectangle "APC23 : Experimentaion de la notion de compilation" as APC23
}

package Competence5 {
rectangle "APC51 : Apprehender les besoins du client et de l'utilisateur" as APC51 
rectangle "APC52 : Mettre en place des outils de gestion de projet" as APC52
}
