@startgantt

title SAE S2.01/04/05

printscale weekly

Project starts the 14th of March 2022


-- SAE S2.05 --

[Liv. CDC] lasts 3 weeks

[Liv. Doc Tec.] starts the 18th of April 2022 
[Liv. Doc Tec.] lasts 1 week

[Liv. Doc Finale] lasts 1 week
[Liv. Doc Finale] starts the 30th of May 2022

[Soutenances/Anglais] lasts 1 week
[Soutenances/Anglais] starts the 6th of June 2022

[Liv. CDC] -> [Liv. Doc Tec.] 
[Liv. Doc Tec.] -> [Liv. Doc Finale]
[Liv. Doc Finale] -> [Soutenances/Anglais]

-- SAE S2.04 --

[Création BD] lasts 3 weeks
[Création BD] starts the 4h of April 2022

[Visulisation] starts the 23th of May 2022
[Visulisation] lasts 2 weeks

[Liv. CDC] -> [Création BD] 
[Création BD] -> [Visulisation]

-- SAE S2.01 --

[Dev. App] starts the 9th of May 2022
[Dev. App] lasts 3 weeks
[Doc. Eval.] lasts 1 week

[Création BD] -> [Dev. App]
[Dev. App] -> [Doc. Eval.] 


@endgantt



14 15 16 Création BD
21 22 Visulisation

