@startgantt 

title SAE S2 (projets)

printscale weekly

Project starts the 17th of January 2022
'17th of January
'14th of March

-- SAE S2.01 Dév. d'application --

[Prés. Projet] starts on the 21st of March 2022
[Prés. Projet] lasts 1 week

[Dev. App V1] starts the 9th of May 2022
[Dev. App V1] lasts 2 weeks

[Doc1. Eval.] lasts 1 week

[Dev. App V1] -> [Doc1. Eval.] 

[Dev. App V2] starts the 23rd of May 2022
[Dev. App V2] lasts 2 weeks

[Dev. App V2] -> [Doc2. Eval.] 
[Doc2. Eval.] lasts 1 week

-- SAE S2.02 Exploration algo. --

[SAE 2.02] lasts 1 weeks
[SAE 2.02] starts the 13th of June 2022

-- SAE S2.03 Inst. services rés. --

[SAE 2.03] lasts 8 weeks
[SAE 2.03] starts the 28th of March 2022

-- SAE S2.04 Exploitation BD --

[Réception BD] lasts 1 weeks
[Réception BD] starts the 2nd of May 2022

[SAE 2.04] lasts 10 weeks
[SAE 2.04] starts the 4th of April 2022

' [Visualisation] starts the 23th of May 2022
' [Visualisation] lasts 2 weeks

' [Réception BD] -> [Visualisation]

-- SAE S2.05 Gestion d'un projet --

[CDC V1] lasts 1 week
[CDC V1] starts the 28th of March 2022

[CDC V2] lasts 1 week
[CDC V2] starts the 18th of April 2022

[CDC V1] -> [CDC V2]

[Liv. Doc Tec.] starts the 16th of May 2022 
[Liv. Doc Tec.] lasts 1 week

[Liv. Doc Finale] lasts 1 week
[Liv. Doc Finale] starts the 30th of May 2022

[Recettes] lasts 1 week
[Recettes] starts the 6th of June 2022

[CDC V2] -> [Liv. Doc Tec.] 
[Liv. Doc Tec.] -> [Liv. Doc Finale]
[Liv. Doc Finale] -> [Recettes]

-- SAE S2.06 Travail d'équipe --

[SAE 2.06] lasts 3 weeks
[SAE 2.06] starts the 16th of May 2022

'-- Liens inter - SAEs --

[Prés. Projet] -> [CDC V1]
[CDC V1] -> [Réception BD] 
[Réception BD] -> [Dev. App V1]


@endgantt


